on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: devops/nginx/dockerfile
          push: true
          tags: my-nginx:latest
          build-args: |
            NGINX_VERSION=1.21.6
            NGINX_PORT=80
      - name: Run Nginx container
        run: |
          docker run -d -p 80:80 my-nginx:latest
          echo "Nginx is running on port 80"