name: nginx-server

on:
  push:
    branches:
      - main
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: devops/nginx/dockerfile
          push: true
          tags: my-nginx:latest

      - name: Run Nginx container
        run: |
          docker run -d -p 80:80 my-nginx
# k